version: '3.8'

services:
  bot:
    build: .
    container_name: training_bot
    restart: unless-stopped
    volumes:
      - ./database.db:/app/database.db
      - .:/app
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}